"""user add tokens

Revision ID: 639e633216c7
Revises: 3330ad58e77e
Create Date: 2020-05-11 10:28:44.431525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639e633216c7'
down_revision = '3330ad58e77e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
