"""add comments_likes table

Revision ID: 839e9a6b0dbc
Revises: f55bd1cc5741
Create Date: 2020-05-25 10:13:04.545014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839e9a6b0dbc'
down_revision = 'f55bd1cc5741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments_likes',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments_likes')
    # ### end Alembic commands ###
